const mongoose = require("mongoose");
const express = require("express");
const router = express.Router();
const User = require("../schema/user.schema.js");
const { authenticateJWT, authorizeRoles } = require("../middlewares/auth.middleware");
const { getAllUsers, createUser, updateUser, deleteUser } = require("../controllers/user.controller");
router.post("/", createUser);
router.use(authenticateJWT);
router.route("/").get(authorizeRoles("admin"),getAllUsers);
router.route("/:id").put(updateUser).delete(authorizeRoles("admin"),deleteUser);
module.exports = router;
